### ISSUE TITLE
[EPIC] Multiple bouncers

### ISSUE THREAD

**Issue by rtnpro** [waartaa/ircb#63]
In 0.2 release, with server side flux implementation, we went multiprocess, i.e., separate `store`, `bouncer`, `cli` and `web` processes. With the basic server side flux framework in place, it's time to go multiple bouncer instances this time. The goal is to:
- distribute IRC bot instances across multiple bouncer instances
- to be fault tolerant, i.e., if a bouncer instance dies, the system must be able to re create the deceased bots in the failed bouncer in the current running bouncers
- implement load balancer for the bouncers

TODOS:
- [ ] Implement dynamic bouncer registration and discovery.
- [ ] Implement a strategy to distribute IRC bots across multiple bouncers (Round Robin would work for now)
- [ ] Implement a registry for IRC bots running in bouncers
- [ ] When a bouncer dies, distribute bots running on it across working bouncers and connect to IRC
- [ ] Load balance across bouncers using `005    RPL_BOUNCE` IRC message as mentioned in https://tools.ietf.org/html/rfc2812

Let's create separate issues for each of the above TODOs and start hacking
